HaragApp/Models/Advertisment.cs
using HaragApp.Data;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;

namespace HaragApp.Models
{
    public class Advertisment
    {
        [Key]
        public int AdID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }

        public bool IsPact { get; set; } = true;

        [ForeignKey("ApplicationDbUser")]
        public string UserId { get; set; }
        public virtual ApplicationDbUser User { get; set; }

        [ForeignKey("City")]
        public int CityID { get; set; }
        public virtual City City { get; set; }

        [ForeignKey("AnimalCategory")]
        public int CategoryID { get; set; }


        public bool IsPaid { get; set; } = false;
        //public string IsPaidDescription { get; set; }


        public virtual AnimalCategory AnimalCategory { get; set; }

        public virtual ICollection<AdImage> AdImages { get; set; }

        public virtual ICollection<Favorite> Favorites { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }


    }
}

HaragApp/ViewModels/ShopViewModel.cs
using HaragApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HaragApp.ViewModels
{
    public class ShopViewModel
    {
        public string search { get; set; }
        public int CategoryId { get; set; }
        public int CityId { get; set; }
        public int? PageNo { get; set; }

        public string userID { get; set; }

        public List<AdsImagesVM2> Advertisments { get; set; }
        public List<AnimalCategory> Categories { get; set; }
        public List<City> Cities { get; set; }
        public int Km { get; set; }
        public double Lang { get; set; }
        public double Lat { get; set; }

        public int AllAdsCount { get; set; }
        public string shopSliderImage { get; set; }

        public int ActiveCity { get; set; }
        public int ActiveCategory { get; set; }
    }
}

HaragApp/Controllers/api/AdvertismentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using HaragApp.Data;
using HaragApp.Models;
using HaragApp.ViewModels;
using HaragApp.Component.Interfaces;
using HaragApp.Component.Services;
using Microsoft.AspNetCore.Identity;
using RestSharp;
using System.Net;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.FileProviders;
using System.Net.Http.Headers;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication.JwtBearer;

namespace HaragApp.Controllers.api
{
   
    [Route("api/[controller]")]
    //[ApiController]
    [Authorize(AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme)]
    public class AdvertismentsController : ControllerBase
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationDbUser> _userManager;
        private IHostingEnvironment _hosting { get; set; }
        public AdvertismentsController(ApplicationDbContext context, IHostingEnvironment hosting, UserManager<ApplicationDbUser> userManager)
        {
            _context = context;
            _userManager = userManager;
            _hosting = hosting;
        }

        // GET: api/Advertisments
        //[HttpGet]
        //public  ActionResult<List<AdsImagesVm>> GetAdvertisments(string userID)
        //{
        //    IAdverstisment ads = new AdvertisementServices(_context);

        //    return ads.GetAllAdvertisemtsData(userID) ;
        //}

        // GET: api/Advertisments/5
        [AllowAnonymous]
        [HttpGet("{id}")]
        public ActionResult<AdsImagesVM2> GetAdvertisment(int id)
        {
           
            //var advertisment = await _context.Advertisments.FindAsync(id);
            IAdverstisment ads = new AdvertisementServices(_context, _hosting);
            var advertisment = ads.Details(id);
            if (advertisment == null)
            {
                return NotFound();
            }

            return advertisment;
        }



        [AllowAnonymous]
        // more details, see https://go.microsoft.com/fwlink/?linkid=2123754.
        [HttpPut]
        public async Task<IActionResult> PutAdvertisment(AdsImagesVm advertisment)
        {

            var img = HttpContext.Request.Form.Files;//instead of ---> advertisment.Files;

            IAdverstisment ads = new AdvertisementServices(_context, _hosting);
            ads.UpdateAsync(advertisment, img);

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                
            }
            AdsImagesVM2 model = new AdsImagesVM2()
            {
                AdID = advertisment.AdID,
                CategoryID = advertisment.CategoryID,
                Title = advertisment.Title,
                CityID = advertisment.CityID,
                IsPaid = advertisment.IsPaid,
                IsPact = advertisment.IsPact,
                IsFav = advertisment.IsFav,
                UserId = advertisment.UserId,
                Description = advertisment.Description,
                ImageUrl1 = advertisment.ImageUrl1,
                ImageUrl2 = advertisment.ImageUrl2,
                ImageUrl3 = advertisment.ImageUrl3,
                ImageUrl4 = advertisment.ImageUrl4,
                ImageUrl5 = advertisment.ImageUrl5
            };

            return CreatedAtAction("GetAdvertisment", new { id = advertisment.AdID }, model);
           // return NoContent();
        }

    
        [AllowAnonymous]
        [HttpPost, DisableRequestSizeLimit]
        public async Task<ActionResult<AdsImagesVm>> PostAdvertisment(AdsImagesVm advertisment)
        {

            var img = HttpContext.Request.Form.Files;//instead of ---> advertisment.Files;

            if (img.Any() ||img.Count >0)
            {
                if (img.Count == 1) { advertisment.ImageUrl2 = advertisment.ImageUrl3 = advertisment.ImageUrl4 = advertisment.ImageUrl5 = $"/Home/images/default.png"; }
                if (img.Count == 2) { advertisment.ImageUrl3 = advertisment.ImageUrl4 = advertisment.ImageUrl5 = $"/Home/images/default.png"; }
                if (img.Count == 3) { advertisment.ImageUrl4 = advertisment.ImageUrl5 = $"/Home/images/default.png"; }
                if (img.Count == 4) { advertisment.ImageUrl5 = $"/Home/images/default.png"; }

                for (int i = 0; i < img.Count; i++)
                {
                    //string result = "defaultRecImage.png";

                    try
                    {

                        string uploads = Path.Combine(_hosting.WebRootPath, @"uploads");
                        var filename = ContentDispositionHeaderValue.Parse(img[i].ContentDisposition).FileName.Trim('"');
                        var newFileName = Guid.NewGuid() + filename;
                        string fullPath = Path.Combine(uploads, newFileName);
                        img[i].CopyTo(new FileStream(fullPath, FileMode.Create));
                        if (i == 0)
                        {
                            advertisment.ImageUrl1 = $"/uploads/{newFileName}";
                        }
                        if (i == 1)
                        {
                            advertisment.ImageUrl2 = $"/uploads/{newFileName}";
                        }
                        if (i == 2)
                        {
                            advertisment.ImageUrl3 = $"/uploads/{newFileName}";
                        }
                        if (i == 3)
                        {
                            advertisment.ImageUrl4 = $"/uploads/{newFileName}";
                        }
                        if (i == 4)
                        {
                            advertisment.ImageUrl5 = $"/uploads/{newFileName}";
                        }

                    }
                    catch (Exception ex)
                    {


                    }
                }

               

                IAdverstisment ads = new AdvertisementServices(_context, _hosting);
                ads.CreateAsync(advertisment);
                AdsImagesVM2 model = new AdsImagesVM2()
                {
                    AdID = advertisment.AdID,
                    CategoryID = advertisment.CategoryID,
                    Title = advertisment.Title,
                    CityID = advertisment.CityID,
                    IsPaid = advertisment.IsPaid,
                    IsPact = advertisment.IsPact,
                    IsFav = advertisment.IsFav,
                    Description = advertisment.Description,
                    ImageUrl1 = advertisment.ImageUrl1,
                    ImageUrl2 = advertisment.ImageUrl2,
                    ImageUrl3 = advertisment.ImageUrl3,
                    ImageUrl4 = advertisment.ImageUrl4,
                    ImageUrl5 = advertisment.ImageUrl5,
                    UserId = advertisment.UserId
                };
                return CreatedAtAction("GetAdvertisment", new { id = advertisment.AdID }, model);
            }
            else
            {


                advertisment.ImageUrl1= advertisment.ImageUrl2 = advertisment.ImageUrl3 = advertisment.ImageUrl4 = advertisment.ImageUrl5 = $"/Home/images/default.png"; 
               

                IAdverstisment ads = new AdvertisementServices(_context, _hosting);
                ads.CreateAsync(advertisment);
                AdsImagesVM2 model = new AdsImagesVM2()
                {
                    AdID = advertisment.AdID,
                    CategoryID = advertisment.CategoryID,
                    Title = advertisment.Title,
                    CityID = advertisment.CityID,
                    IsPaid = advertisment.IsPaid,
                    IsPact = advertisment.IsPact,
                    IsFav = advertisment.IsFav,
                    Description = advertisment.Description,
                    ImageUrl1 = advertisment.ImageUrl1,
                    ImageUrl2 = advertisment.ImageUrl2,
                    ImageUrl3 = advertisment.ImageUrl3,
                    ImageUrl4 = advertisment.ImageUrl4,
                    ImageUrl5 = advertisment.ImageUrl5,
                    UserId = advertisment.UserId
                };
                return CreatedAtAction("GetAdvertisment", new { id = advertisment.AdID }, model);
            }


            return NotFound();
        }

        // DELETE: api/Advertisments/5
        [HttpDelete("{id}")]
        [AllowAnonymous]
        public async Task<ActionResult<Advertisment>> DeleteAdvertisment(int id)
        {
            var advertisment = await _context.Advertisments.FindAsync(id);
            if (advertisment == null)
            {
                return NotFound();
            }

            _context.Advertisments.Remove(advertisment);
            await _context.SaveChangesAsync();

            return advertisment;
        }

        

        private bool AdvertismentExists(int id)
        {
            return _context.Advertisments.Any(e => e.AdID == id);
        }
    }
}

HaragApp/Views/Advertisments/Create.cshtml
@model HaragApp.ViewModels.AdsImagesVm
@{
	Layout = "~/Views/Shared/_LayoutHome.cshtml";
	<style>
		input[type="file"] {
			color: transparent;
		}

	</style>
}



<!--Page Title-->
<section class="page-title" style="background-image:url(@ViewBag.SliderImage);">
	<div class="auto-container">
		<div class="inner-container clearfix">
			<h1>إضافة إعلان </h1>
			
		</div>
	</div>
</section>
<!--End Page Title-->
<!--Login Section-->

<section class="login-section">
	<div class="auto-container">
		<div class="row clearfix rtl-dir">
		 
			<div class="column col-lg-12 col-md-12 col-sm-12 ">
				<!-- Login Form -->
				<h2>إضافه إعلان  </h2>
				<div class="login-form text-right">
					<!--Login Form-->
					<form asp-action="Create" asp-controller="Advertisments" method="post" id="createform">
						<div class="form-group">
							<label>الاسم   </label>
							<input  class="form-control" asp-for="Title" placeholder="الاسم" required>
						</div>

						<div class="form-group">
							<label>المدينه</label>
							<select class="form-control h-25" asp-items="@ViewBag.CityID as SelectList" asp-for="CityID" required>
								<option value="-1">اختر مدينه</option>
							</select>

						</div>
						<div class="form-group">
							<label>الصنف</label>
							<select class="form-control h-25" asp-items="@ViewBag.CategoryID as SelectList" asp-for="CategoryID" required>
								<option value="-1">اختر صنف</option>
							</select>

						</div>
						<div class="form-group">
							<label for="exampleFormControlTextarea1">التفاصيل</label>
							<textarea class="form-control" id="exampleFormControlTextarea1" rows="3" type="text" asp-for="Description" required></textarea>
						</div>
						<div class="form-group">

							<input type="checkbox" id="vehicle1" asp-for="IsPact" required>
							<input type="checkbox" id="vehicle1" asp-for="IsPaid" style="display: none">
							<label for="vehicle1">اتعهد بدفع 15ريال فى كل راس يتم بيعه عن طريق الموقع</label><br>

						</div>
                        
						<div class="row justify-content-center">
							<div class="col-lg-2 col-md-6 col-sm-12">
								<label>الصورة الاولى</label>
								<input type="file" required id="files1" name="files" class="btn btn-block" >
								<img id="SelectedImage1" src="~/Home/images/default.png" class="img-thumbnail align-content-center" style="width:100px;height:100px;" /><img id="loader1" src="~/assets/img/lodingLoader.gif" style="width:30px;height:30px;display:none" />
							</div>

							<div class="col-lg-2 col-md-6 col-sm-12">
								<label>الصورة الثانيه</label>
								<input type="file" id="files2" name="files" required class="btn btn-block">
								<img id="SelectedImage2" src="~/Home/images/default.png" class="img-thumbnail align-content-center" style="width:100px;height:100px;" /><img id="loader2" src="~/assets/img/lodingLoader.gif" style="width:30px;height:30px;display:none" />
							</div>
							<div class="col-lg-2 col-md-6 col-sm-12">
								<label>الصورة الثالثه</label>
								<input type="file" id="files3" name="files" required class="btn btn-block">
								<img id="SelectedImage3" src="~/Home/images/default.png" class="img-thumbnail align-content-center" style="width:100px;height:100px;" /><img id="loader3" src="~/assets/img/lodingLoader.gif" style="width:30px;height:30px;display:none" />
							</div>
							<div class="col-lg-2 col-md-6 col-sm-12">
								<label>الصورة الرابعه</label>
								<input type="file" id="files4" name="files" required class="btn btn-block">
								<img id="SelectedImage4" src="~/Home/images/default.png" class="img-thumbnail align-content-center" style="width:100px;height:100px;" /><img id="loader4" src="~/assets/img/lodingLoader.gif" style="width:30px;height:30px;display:none" />
							</div>
							<div class="col-lg-2 col-md-6 col-sm-12">
								<label>الصورةالخامسه</label>
								<input type="file" id="files5" name="files" required class="btn btn-block">
								<img id="SelectedImage5" src="~/Home/images/default.png" class="img-thumbnail align-content-center" style="width:100px;height:100px;" /><img id="loader5" src="~/assets/img/lodingLoader.gif" style="width:30px;height:30px;display:none"/>
							</div>
						</div>


						<br />
						<br />
						<br />

						<div class="clearfix">
							<div class="pull-left">
								<div class="form-group text-right">
									<button class="theme-btn btn-style-one" type="button" name="submit-form" id="save">تأكيــد </button>
								</div>
							</div>
							
						</div>
						<input id="ImageUrl1" name="ImageUrl1" type="hidden" value="/Home/images/default.png" />
						<input id="ImageUrl2" name="ImageUrl2" type="hidden" value="/Home/images/default.png" />
						<input id="ImageUrl3" name="ImageUrl3" type="hidden" value="/Home/images/default.png" />
						<input id="ImageUrl4" name="ImageUrl4" type="hidden" value="/Home/images/default.png" />
						<input id="ImageUrl5" name="ImageUrl5" type="hidden" value="/Home/images/default.png"  />
					</form>
				</div>
			</div>


		</div>
	</div>
</section>



@section Scripts {
	@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

	<script>
		$("#files1").change(function () {
			$("#loader1").show();
			
			  var element = this;

			  var formData = new FormData();

		 var totalFiles = element.files.length;

			  for (var i = 0; i < totalFiles; i++) {
				var file = element.files[i];
				formData.append("Photo", file);
			  }

				$.ajax({
					type: 'POST',
					url: '@Url.Action("UploadImage", "Advertisments")',
					dataType: 'json',
					data: formData,
					contentType: false,
					processData: false,
					success: function (response) {
						$("#ImageUrl1").val(response.image);
						$("#SelectedImage1").attr("src", response.image);
						$("#loader1").hide();
                       
					},
					error: function () {
						alert("FAIL");
					}
				})
				//.done(function (response) {

				//        alert(response.ImageURL)
				//       // $("#ImageUrl").val(response.ImageURL);
				//      //  $("#SelectedImage").attr("src", response.ImageURL);

				// })
				//.fail(function (XMLHttpRequest, textStatus, errorThrown) {
				//    	alert("FAIL");
				//});
	 });
		$("#files2").change(function () {
		 $("#loader2").show();
			  var element = this;

			  var formData = new FormData();

		 var totalFiles = element.files.length;

			  for (var i = 0; i < totalFiles; i++) {
				var file = element.files[i];
				formData.append("Photo", file);
			  }

				$.ajax({
					type: 'POST',
					url: '@Url.Action("UploadImage", "Advertisments")',
					dataType: 'json',
					data: formData,
					contentType: false,
					processData: false,
					success: function (response) {
						$("#ImageUrl2").val(response.image);
						$("#SelectedImage2").attr("src", response.image);
						$("#loader2").hide();
					},
					error: function () {
						alert("FAIL");
					}
				})
				//.done(function (response) {

				//        alert(response.ImageURL)
				//       // $("#ImageUrl").val(response.ImageURL);
				//      //  $("#SelectedImage").attr("src", response.ImageURL);

				// })
				//.fail(function (XMLHttpRequest, textStatus, errorThrown) {
				//    	alert("FAIL");
				//});
	 });
		$("#files3").change(function () {
		 $("#loader3").show();
			  var element = this;

			  var formData = new FormData();

		 var totalFiles = element.files.length;

			  for (var i = 0; i < totalFiles; i++) {
				var file = element.files[i];
				formData.append("Photo", file);
			  }

				$.ajax({
					type: 'POST',
					url: '@Url.Action("UploadImage", "Advertisments")',
					dataType: 'json',
					data: formData,
					contentType: false,
					processData: false,
					success: function (response) {
						$("#ImageUrl3").val(response.image);
						$("#SelectedImage3").attr("src", response.image);
						$("#loader3").hide();
					},
					error: function () {
						alert("FAIL");
					}
				})
				//.done(function (response) {

				//        alert(response.ImageURL)
				//       // $("#ImageUrl").val(response.ImageURL);
				//      //  $("#SelectedImage").attr("src", response.ImageURL);

				// })
				//.fail(function (XMLHttpRequest, textStatus, errorThrown) {
				//    	alert("FAIL");
				//});
	});
		$("#files4").change(function () {
		 $("#loader4").show();
			  var element = this;

			  var formData = new FormData();

		 var totalFiles = element.files.length;

			  for (var i = 0; i < totalFiles; i++) {
				var file = element.files[i];
				formData.append("Photo", file);
			  }

				$.ajax({
					type: 'POST',
					url: '@Url.Action("UploadImage", "Advertisments")',
					dataType: 'json',
					data: formData,
					contentType: false,
					processData: false,
					success: function (response) {
						$("#ImageUrl4").val(response.image);
						$("#SelectedImage4").attr("src", response.image);
						$("#loader4").hide();
					},
					error: function () {
						alert("FAIL");
					}
				})
				//.done(function (response) {

				//        alert(response.ImageURL)
				//       // $("#ImageUrl").val(response.ImageURL);
				//      //  $("#SelectedImage").attr("src", response.ImageURL);

				// })
				//.fail(function (XMLHttpRequest, textStatus, errorThrown) {
				//    	alert("FAIL");
				//});
	});
		$("#files5").change(function () {
		 $("#loader5").show();
			  var element = this;

			  var formData = new FormData();

		 var totalFiles = element.files.length;

			  for (var i = 0; i < totalFiles; i++) {
				var file = element.files[i];
				formData.append("Photo", file);
			  }

				$.ajax({
					type: 'POST',
					url: '@Url.Action("UploadImage", "Advertisments")',
					dataType: 'json',
					data: formData,
					contentType: false,
					processData: false,
					success: function (response) {
						$("#ImageUrl5").val(response.image);
						$("#SelectedImage5").attr("src", response.image);
						$("#loader5").hide();
					},
					error: function () {
						alert("FAIL");
					}
				})
				//.done(function (response) {

				//        alert(response.ImageURL)
				//       // $("#ImageUrl").val(response.ImageURL);
				//      //  $("#SelectedImage").attr("src", response.ImageURL);

				// })
				//.fail(function (XMLHttpRequest, textStatus, errorThrown) {
				//    	alert("FAIL");
				//});
	 });


		$("#save").click(function () {			//if ($("#ImageUrl1").val() != "" && $("#ImageUrl2").val() != "" && $("#ImageUrl3").val() != "" && $("#ImageUrl4").val() != "" && $("#ImageUrl5").val() != "") {			//	$("#createform").submit();
			//} else {			//	alert("Please wait files are still UPLOADING !!")
			//}            if ($("#loader1").is(":hidden") && $("#loader2").is(":hidden") && $("#loader3").is(":hidden")&& $("#loader4").is(":hidden")&& $("#loader5").is(":hidden")) {
				
				$("#createform").submit();
            } else {
				alert("برجاء الانتظار حتى يتم تحميل الصور")
               
            }			});

	</script>
}

HaragApp/Views/Advertisments/CreatePaidAdd.cshtml
	@model HaragApp.ViewModels.AdsImagesVm
@{
	ViewData["Title"] = "CreatePaidAdd";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
	<section class="login-section">
		<div class="auto-container">
			<div class="row clearfix">

				<div class="column col-lg-12 col-md-12 col-sm-12 ">
					<!-- Login Form --><br /><br />
					<h2>إضافه اعلان ممول </h2>
					<h3 style="text-align:center">(ارفق Https او Http قبل اسم الرابط المراد الوصول اليه)</h3>
					<h4 style="text-align:center"><span class="text-danger">https://</span>www.google.com</h4>

					<div class="login-form text-right">
						<!--Login Form-->
						<form asp-action="CreatePaidAdd" method="post" id="createform">
							<div class="form-group">

								<input class="form-control" asp-for="Title" placeholder="الاسم  " required>
							</div>

							<div class="form-group">
								<input class="form-control" id="exampleFormControlTextarea1" placeholder="رابط الإعلان الممول(برجاء ارفاق https مع رابط الموقع) " type="text" asp-for="Description">
							</div>
							<div class="form-group" style="display:none">
								<input type="checkbox" id="vehicle1" asp-for="IsPaid" checked="checked">
								<input type="checkbox" id="vehicle1" asp-for="IsPact" checked="checked">

							</div>

							<div class="row">
								<label>صورة الإعــلان</label>
								<input type="file" required id="files1" name="files" class="btn btn-block w-50 mb-2 m-auto">
								<img id="SelectedImage1" class="img-thumbnail align-content-center m-auto" style="height:auto;" /> <img id="loader1" src="~/assets/img/lodingLoader.gif" style="width:30px;height:30px;display:none" />
							</div>


							<br />
							<br />
							<br />

							<div class="clearfix">
								<div class="pull-left">
									<div class="form-group text-right">
										<button class="btn btn-primary" type="button" name="submit-form" id="save">تأكيــد </button>
									</div>
								</div>
							</div>
							<input id="ImageUrl1" name="ImageUrl1" type="hidden" value="" />
						</form>
					</div>
					<!--End Login Form -->
				</div>


			</div>
		</div>
	</section>
</div>

@section Scripts {
	@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

	<script>
        $("#files1").change(function () {
		 $("#loader1").show();
			  var element = this;

			  var formData = new FormData();

		 var totalFiles = element.files.length;

			  for (var i = 0; i < totalFiles; i++) {
				var file = element.files[i];
				formData.append("Photo", file);
			  }

				$.ajax({
					type: 'POST',
					url: '@Url.Action("UploadImage", "Advertisments")',
					dataType: 'json',
					data: formData,
					contentType: false,
					processData: false,
					success: function (response) {
						$("#ImageUrl1").val(response.image);
                        $("#SelectedImage1").attr("src", response.image);
						$("#loader1").hide();
					},
					error: function () {
						alert("FAIL");
					}
				})
        });

		$("#save").click(function () {            if ($("#ImageUrl1").val() != "") {                $("#createform").submit();
            } else {                alert("Please wait files are still UPLOADING !!")
            }        });


	</script>
}

HaragApp/Views/Advertisments/GetUserAds.cshtml
@model IEnumerable<HaragApp.ViewModels.AdsImagesVM2>
@{
    ViewData["Title"] = "GetUserAds";
    Layout = "~/Views/Shared/_LayoutHome.cshtml";
}

    <div class="container">
        <h2 class="text-right mt-3 mb-3">إعلاناتـــي</h2>

        <div class="row">
            @foreach (var item in Model)
            {
                <div class="col-sm-6 mb-2">
                    <div class="card">
                        <div class="row card-body">
                            <div class="col-6">
                                <h5 class="card-title" style="text-align:right;"><a asp-action="Details" asp-controller="Advertisments" asp-route-id="@item.AdID">@item.Title</a></h5>
                                <p class="card-text mb-2" style="text-align:right;text-overflow: ellipsis; overflow: hidden;  white-space: nowrap; width:100%;">@item.Description</p>

                            </div>
                            <img class="col-md-6 col-sm-12 img-thumbnail" style="height:200px;width:100%" src="@item.ImageUrl1" alt="sans" />
                        </div>
                        <div style="text-align:right;">
                            <a class="btn btn-primary btn-block" style="text-align:center;" asp-action="userUpdateADV" asp-controller="Advertisments" asp-route-id="@item.AdID">تعديــل</a>
                            <a class="btn btn-danger btn-block" style="text-align:center;" asp-action="userDeleteADV" asp-controller="Advertisments" asp-route-id="@item.AdID">حــذف</a>
                        </div>
                    </div>
                </div>
            }
        </div>

HaragApp/Views/Advertisments/ShowFavourite.cshtml
@model ICollection<HaragApp.ViewModels.favoriteViewModel>
@{
    ViewData["Title"] = "ShowFavourite";
    Layout = "~/Views/Shared/_LayoutHome.cshtml";
}

    <div class="container">
        <h2 class="text-right mt-3 mb-3">المفضلــة</h2>

        <div class="row">
            @foreach (var item in Model)
            {
                <div class="col-sm-6 mb-2">
                    <div class="card">
                        <div class="row card-body">
                            <div class="col-md-6 col-sm-12">
                                <h5 class="card-title" style="text-align:right;"><a asp-action="Details" asp-controller="Advertisments" asp-route-id="@item.AdID">@item.Title</a></h5>
                                <p class="card-text mb-2" style="text-align:right;"> المنطقة : @item.CityName</p>
                                <p class="card-text mb-2" style="text-align:right;">الصنف : @item.CategoryName</p>

                            </div>
                            <img class="col-md-6 col-sm-12 img-thumbnail" style="height:200px;width:100%" src="@item.ImageUrl1" alt="sans" />
                        </div>
                        <div style="text-align:right;">
                            <a class="btn btn-danger btn-block" style="text-align:center;" asp-action="DeleteFav" asp-controller="Advertisments" asp-route-id="@item.AdID"> حــذف من المفضلــة</a>
                        </div>
                    </div>
                </div>
            }
        </div>

HaragApp/Views/Advertisments/getAllAdvertinsmets.cshtml
@model List<Advertisment>
@{
    var categories = ViewBag.categories as List<AnimalCategory>;
    var Cities = ViewBag.Cities as List<City>;

    var CategoryId = ViewBag.CategoryId;
    var search = ViewBag.search;
    var CityId = ViewBag.CityId;
}